''' <summary>
''' 2019.7.26
''' 常用的常量类
''' </summary>
Public NotInheritable Class Constants
    Public Const CHARSET_UTF8 As String = "utf-8"
    Public Const DATE_TIME_FORMAT As String = "yyyy-MM-dd HH:mm:ss"
    Public Const DATE_TIME_MS_FORMAT As String = "yyyy-MM-dd HH:mm:ss.fff"
    Public Const SIGN_METHOD_MD5 As String = "md5"
    Public Const SIGN_METHOD_HMAC As String = "hmac"
    Public Const SIGN_METHOD_HMAC_SHA256 As String = "hmac-sha256"
    Public Const LOG_SPLIT As String = "^_^"
    Public Const LOG_FILE_NAME As String = "topsdk.log"
    Public Const ACCEPT_ENCODING As String = "Accept-Encoding"
    Public Const CONTENT_ENCODING As String = "Content-Encoding"
    Public Const CONTENT_ENCODING_GZIP As String = "gzip"
    Public Const ERROR_RESPONSE As String = "error_response"
    Public Const ERROR_CODE As String = "code"
    Public Const ERROR_MSG As String = "msg"
    Public Const QIMEN_CLOUD_ERROR_RESPONSE As String = "response"
    Public Const QIMEN_CLOUD_ERROR_CODE As String = "code"
    Public Const QIMEN_CLOUD_ERROR_MSG As String = "message"
    Public Const SDK_VERSION As String = "top-sdk-net-20190715"
    Public Const SDK_VERSION_CLUSTER As String = "top-sdk-net-cluster-20190715"
    Public Const APP_KEY As String = "app_key"
    Public Const FORMAT As String = "format"
    Public Const METHOD As String = "method"
    Public Const TIMESTAMP As String = "timestamp"
    Public Const VERSION As String = "v"
    Public Const SIGN As String = "sign"
    Public Const SIGN_METHOD As String = "sign_method"
    Public Const PARTNER_ID As String = "partner_id"
    Public Const SESSION As String = "session"
    Public Const FORMAT_XML As String = "xml"
    Public Const FORMAT_JSON As String = "json"
    Public Const SIMPLIFY As String = "simplify"
    Public Const TARGET_APP_KEY As String = "target_app_key"
    Public Const QM_ROOT_TAG_REQ As String = "request"
    Public Const QM_ROOT_TAG_RSP As String = "response"
    Public Const QM_CUSTOMER_ID As String = "customerId"
    Public Const QM_CONTENT_TYPE As String = "text/xml;charset=utf-8"
    Public Const QM_TARGETAPPKEY As String = "targetAppkey"
    Public Const CTYPE_DEFAULT As String = "application/octet-stream"
    Public Const CTYPE_FORM_DATA As String = "application/x-www-form-urlencoded"
    Public Const CTYPE_FILE_UPLOAD As String = "multipart/form-data"
    Public Const CTYPE_TEXT_XML As String = "text/xml"
    Public Const CTYPE_TEXT_PLAIN As String = "text/plain"
    Public Const CTYPE_APP_JSON As String = "application/json"
    Public Const READ_BUFFER_SIZE As Integer = 1024 * 4
End Class

